server:
  port: 8080
  host: 127.0.0.1
logging:
  llm_request_debug_enabled: false
chat:
  whitelist_enabled: true
client_ip:
  real_ip_enabled: false
  real_ip_header: X-Forwarded-For
admin:
  username: admin
  password: admin
providers:
- name: deepseek
  enabled: true
  api: https://api.deepseek.com/chat/completions
  source_format: openai_chat
  api_key: sk-1234
  verify_ssl: false
  model_list:
  - deepseek-v4-flash
  - deepseek-v4-pro
  proxy_mode: direct
auth_groups:
- name: group1
  strategy: least_inflight
  cooldown_seconds_on_429: 60
  entries:
  - id: key1
    enabled: true
    headers:
      Authorization: Bearer 1
oauth:
  enabled: true
  proxy: ''
  verify_ssl: false
  proxy_mode: direct
api_keys:
  enabled: true
